POST http://localhost:3001/reports
content-type: application/json

{
  "make": "toyota",
  "model": "corolla",
  "year": 2019,
  "mileage": 2000,
  "lng": 13,
  "lat": 27,
  "price": 70000
}


### approve reports
PATCH http://localhost:3001/reports/9
content-type: application/json

{
  "approved": true
}


### Get estimate
GET  http://localhost:3001/reports?make=toyota&model=corolla&lng=0&lat=0&mileage=120000&year=1980
