POST http://localhost:3000/auth/signup
content-type: application/json

{
    "email": "email3@email.com",
    "password": "password3"
}

### Get user
GET http://localhost:3000/auth/2


### Get user by email
GET http://localhost:3000/auth?email=email2444@email.com

### Delete user
DELETE http://localhost:3000/auth/4re43523r

### Update user
PATCH http://localhost:3000/auth/293847928984
content-type: application/json

{
    "email": "email2@email.com",
    "password": "password2"
}